spring:
  application:
    name: gpitf-purchasing
  datasource:
    url: jdbc:postgresql://localhost:4001/postgres
    username: postgres
    password: 
    driver-class-name: org.postgresql.Driver
  messages:
    basename: messages/web
    encoding: UTF-8
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
#    show-sql: true
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

onboarding.api.url: http://localhost:5100
spring.jackson.serialization.write-dates-as-timestamps: false

server.servlet.session.timeout: 3600s # Session timeout. If a duration suffix is not specified, seconds will be used.
server.port: 8220

spring.session.store-type: redis
spring.session.redis.flush-mode: on-save # Sessions flush mode.
spring.session.redis.namespace: spring:session # Namespace for keys used to store sessions.
spring.redis.host: localhost # Redis server host.
#spring.redis.password= # Login password of the redis server.
spring.redis.port: 6379 # Redis server port.

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: catalogue-private-beta-ci
      clientSecret: ptjqjbxbdxryshjbsqelfwoonibgnnee
      accessTokenUri: http://localhost:9000/token
      userAuthorizationUri: http://localhost:9000/auth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
      scope: openid email
    resource:
      userInfoUri: http://localhost:9000/me
    sso:
      login-path: /login

#show sql statement
#logging.level.org.hibernate.SQL: debug
logging.level.org.springframework: info

#show sql values
#logging.level.org.hibernate.type.descriptor.sql: trace
logging.level.uk.nhs.gpitf.purchasing: INFO

#management.endpoints.web.exposure.include: loggers
#endpoints.loggers.sensitive: false


management:
 endpoints:
   web:
     exposure:
       include: loggers
     base-path: /
     path-mapping:
       loggers: /loggers


sysparam.shortlist.max: 14							## Default 4. This should be the default value in Prod
sysparam.directaward.maxvalue: 40000
sysparam.oncatalogue.maxvalue: 250000
sysparam.writeOnboardingCache: false    			## Default false. Set to true to write to  resources/onboardingCache json files
sysparam.readOnboardingCache: false     			## Default false. Set to true to read from resources/onboardingCache json files
sysparam.addDocManToBundles: false					## Default false. This is a temporary flag to add DocMan to bundles. This should be the default value or removed in Prod or later development
sysparam.foundationSearchAddCapabilities: false		## Default false. Foundation search will have additional capabilities available as a filter. In Drop 2 this is expected to be "true"
sysparam.initialFrameworkId: 5A8D06DD-8C32-4821-AC65-BD47294ACD8E

 